[[headers]]
  for = "/*"
  [headers.values]
    "Content-Type" = "application/javascript; charset=utf-8"
    "X-Content-Type-Options" = "nosniff"

[[headers]]
  for = "*.jsx"
  [headers.values]
    "Content-Type" = "application/javascript"